title: carabalg's homepage
description: GitHub Pages example for promoting a project
github_username: carabalg3474
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
